###

GET {{host}}/v1/users?projection=users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjE3YTAxZGM0OTg3YjVjYmIwNDZmNDIiLCJyb2xlIjoiQ1VTVE9NRVIiLCJlbWFpbCI6InZhc2VrQHNlem5hbS5jeiIsInBob25lIjoiNzUzIDM1NyA1NzgiLCJuYW1lIjoiVsOhY2xhdiIsInN1cm5hbWUiOiJCdcWZaWwiLCJhZGRyZXNzIjoiZmRzZDUxNiIsImNpdHkiOiJSeWNobm92IG5hZCBrbsSbxb5ub3UiLCJ6aXBfY29kZSI6IjUxNjAxIiwiX192IjowLCJpYXQiOjE3MTI5MjQ0NzcsImV4cCI6MTcxMjkyODA3N30.wtfqwrmM4UrpZeLVy4RFbMqzjMqbpQptxnsXfVMuOUo
###

GET {{host}}/v1/users/6617a01dc4987b5cbb046f42
Authorization: Bearer {{token}}

###

POST {{host}}/v1/users
Content-Type: application/json

{
    "typ": "CUSTOMER",
    "name": "Pepa",
    "surname": "Novák",
    "email": "pepanovak@gmail.com",
    "phone": "+420777111222",
    "password": "heslo",
    "address": "Hradecká 10",
    "city": "Hradec Králové",
    "zip_code": "264 01",
    "google_access_token_timestamp": "2010-03-10T23:44:56.289Z",
    "google_refresh_token": "google_refresh_token",
    "google_refresh_token_timestamp": "2010-03-10T23:44:56.289Z"
}

###

PUT {{host}}/v1/users/65e366735cfda5f11b930c5d
Content-Type: application/json

{
  "typ": "CUSTOMER",
  "name": "Honza",
  "surname": "Novotný",
  "email": "honzanovotny@gmail.com",
  "phone": "+420777333444",
  "password": "heslo2",
  "address": "Hradecká 12",
  "city": "Hradec Králové",
  "zip_code": "264 01",
  "google_access_token_timestamp": "2010-03-10T23:44:56.289Z",
  "google_refresh_token": "google_refresh_token",
  "google_refresh_token_timestamp": "2010-03-10T23:44:56.289Z"
}


###

DELETE {{host}}/v1/users/65fd9ed67ddd859495ec3878


###

POST localhost:3004/v1/auth/login
Content-Type: application/json

{
    "email": "pepanovak@gmail.com",
    "password": "heslo"
}


###

POST localhost:3000/users-service/v1/auth/login
Content-Type: application/json

{
  "email": "pepanovak@gmail.com",
  "password": "heslo"
}

###

GET localhost:3000/users-service/v1

###

POST localhost:3000/users-service/v1/users
Content-Type: application/json

{
  "typ": "CUSTOMER",
  "name": "Pepa",
  "surname": "Novák",
  "email": "pepanovak@gmail.com",
  "phone": "+420777111222",
  "password": "heslo",
  "address": "Hradecká 10",
  "city": "Hradec Králové",
  "zip_code": "264 01",
  "google_access_token_timestamp": "2010-03-10T23:44:56.289Z",
  "google_refresh_token": "google_refresh_token",
  "google_refresh_token_timestamp": "2010-03-10T23:44:56.289Z"
}