###

GET {{host}}/v1/animals
Authorization: Bearer {{token}}

###

GET {{host}}/v1/
Authorization: Bearer {{token}}

###

GET {{host}}/v1/animals/65ec342d31c26ad8bfd61691
Authorization: Bearer {{token}}


###

POST {{host}}/v1/animals
Content-Type: application/json

{
    "species": "krokodýl1",
    "sex": "male",
    "name": "Honza",
    "birthDate": "2010-03-10T23:44:56.289Z",
    "deathDate": null,
    "owner": "65e352d6d67152adb841fde2"
}

###

PUT {{host}}/v1/animals/66194e4f76b9a38659855f99
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "species": "krokodýl5",
    "sex": "male",
    "name": "Pežot",
    "birthDate": "2010-03-10T23:44:56.289Z",
    "deathDate": null,
    "owner": "65e352d6d67152adb841fde2"
}


###

DELETE {{host}}/v1/animals/65e366735cfda5f11b930c5d

###

GET {{host}}/v1/animals/client/6617a01dc4987b5cbb046f42
Authorization: Bearer {{token}}